project: oz91
queue: normal
walltime: 05:00:00
jobname: mom6_01
ncpus: 4415
jobfs: 100GB

# change to a project you have access to
shortpath: /scratch/x77

model: mom6
input:
    - /g/data/x77/ahg157/inputs/mom6/global-01/
    - /g/data/ik11/inputs/JRA-55/RYF/v1-3/
exe: /g/data/x77/ahg157/exes/MOM6_SIS2/symmetric_FMS1-9d184bdf

collate: false
runlog: true
storage:
  gdata:
    - ik11
    - x77

platform:
  nodesize: 48

mpi:
  module: openmpi/4.1.2

userscripts:
  error: resub.sh
  archive: qsub sync_output_to_gdata.sh
