# change to your project with compute time available
project: g40
queue: normal
walltime: 06:00:00
jobname: mom6_panan_01
ncpus: 962
jobfs: 10GB

# change to a project you have access to
# shortpath: x77

model: mom6
input:
    - /g/data/ik11/inputs/mom6/panan-01/
    - /g/data/ik11/inputs/mom6/regrid_runoff/
    - /g/data/ik11/inputs/JRA-55/RYF/v1-3/
exe: /g/data/ik11/inputs/mom6/bin/symmetric_FMS2-e7d09b7

collate: false
runlog: true
storage:
  gdata:
    - ik11

platform:
  nodesize: 48

mpi:
  module: openmpi/4.1.2
