format: yamanifest
version: 1.0
---
work/MOM6:
  fullpath: /home/157/ahg157/repos/mom6/build/ice_ocean_SIS2_symmetric_debug/MOM6
  hashes:
    binhash: 74bfa07aac60c72218b539d92b25fb56
    md5: 66072721ec81e20466dbeeba9efcea29
